# Generated by Django 5.1.6 on 2025-02-15 18:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='maps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_data', models.CharField(max_length=1000)),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='date published')),
            ],
        ),
        migrations.DeleteModel(
            name='MultipleChoiceOption',
        ),
        migrations.DeleteModel(
            name='MultipleChoiceQuestion',
        ),
    ]
