# Generated by Django 5.1.6 on 2025-02-15 20:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_maps_delete_multiplechoiceoption_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maps',
            name='map_data',
        ),
        migrations.RemoveField(
            model_name='maps',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='maps',
            name='data',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), size=3), default=[[0, 0, 0], [0, 0, 0], [0, 0, 0]], size=3),
        ),
        migrations.AddField(
            model_name='maps',
            name='name',
            field=models.CharField(default='Unnamed Grid', max_length=200),
        ),
    ]
