# Generated by Django 5.1.6 on 2025-02-15 20:31

import django.contrib.postgres.fields
import map.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_remove_maps_map_data_remove_maps_pub_date_maps_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maps',
            name='data',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), size=3), default=map.models.default_grid, size=3),
        ),
    ]
