# Generated by Django 5.1.6 on 2025-02-15 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_alter_maps_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maps',
            name='data',
            field=models.CharField(default='Grid object', max_length=500),
        ),
    ]
