# Generated by Django 5.1.6 on 2025-02-15 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_alter_maps_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maps',
            name='name',
        ),
    ]
