# Generated by Django 5.1.6 on 2025-02-15 22:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_remove_maps_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='maps',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='date published'),
        ),
    ]
