# Generated by Django 5.1.6 on 2025-02-15 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0007_maps_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maps',
            name='pub_date',
        ),
    ]
