# Generated by Django 5.1.6 on 2025-02-16 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='react',
            name='detail',
        ),
        migrations.RemoveField(
            model_name='react',
            name='name',
        ),
        migrations.AddField(
            model_name='react',
            name='grid',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
